version: 2
jobs:
  build:
    docker:
      - image: rhinogram/node-awscli
    steps:
      - checkout
      - run:
          name: Dependency
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py --user
            pip install awscli --upgrade --user
      - run:
          name: Create Package
          command: |
            cd src
            zip -r ../package.zip . 
      - run:
          name: Sync Repos and S3
          command: aws s3 cp package.zip s3://facebook-data-export/
      - run:
          name: Create(or Update) Function on Lamdba
          command: |
            aws lambda update-function-code --function-name getFacebookPostData --s3-bucket facebook-data-export --s3-key package.zip --region ap-northeast-1

